### ISSUE TITLE
Add Environment Variable Support

### ISSUE THREAD

**Issue by russoj88** [steverusso/goclap#34]
I like the idea of using comments to get program configuration, but I use environment variables instead of command line arguments. Can goclap support this, similar to [env](https://github.com/caarlos0/env)?

**Comment by steverusso** [comment]
As a first iteration, support will follow what _seems_ to be [a loose standard](https://stackoverflow.com/questions/11077223/what-order-of-reading-configuration-values) of command line options taking priority over environment variables.

Future iterations of this feature might involve custom ordering or adhering to the order of the configurations.
