### ISSUE TITLE
Add an Extension to Generated Code File

### ISSUE THREAD

**Issue by russoj88** [steverusso/goclap#35]
To make it additionally obvious that the generated code file is generated, can goclap add a file extension (ex: `file.gen.go`)?

As an example, [protobuf's](https://protobuf.dev/reference/go/go-generated/) generated files have `pb` in their name (ex: `file.pb.go`).

**Comment by steverusso** [comment]
Yes good call, and I like `.gen.go`.

The `--out` option exists for those who want a good ole `.go` file.
